//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.11 at 08:31:08 am CET 
//


package allapis.springbootsoap.com;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the allapis.springbootsoap.com package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: allapis.springbootsoap.com
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddEnseignantRequest }
     * 
     */
    public AddEnseignantRequest createAddEnseignantRequest() {
        return new AddEnseignantRequest();
    }

    /**
     * Create an instance of {@link UpdateEnseignantResponse }
     * 
     */
    public UpdateEnseignantResponse createUpdateEnseignantResponse() {
        return new UpdateEnseignantResponse();
    }

    /**
     * Create an instance of {@link UpdateEnseignantRequest }
     * 
     */
    public UpdateEnseignantRequest createUpdateEnseignantRequest() {
        return new UpdateEnseignantRequest();
    }

    /**
     * Create an instance of {@link DeleteEnseignantRequest }
     * 
     */
    public DeleteEnseignantRequest createDeleteEnseignantRequest() {
        return new DeleteEnseignantRequest();
    }

    /**
     * Create an instance of {@link DeleteEnseignantResponse }
     * 
     */
    public DeleteEnseignantResponse createDeleteEnseignantResponse() {
        return new DeleteEnseignantResponse();
    }

    /**
     * Create an instance of {@link AddEnseignantResponse }
     * 
     */
    public AddEnseignantResponse createAddEnseignantResponse() {
        return new AddEnseignantResponse();
    }

    /**
     * Create an instance of {@link EnseignantInfo }
     * 
     */
    public EnseignantInfo createEnseignantInfo() {
        return new EnseignantInfo();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetEnseignantResponse }
     * 
     */
    public GetEnseignantResponse createGetEnseignantResponse() {
        return new GetEnseignantResponse();
    }

    /**
     * Create an instance of {@link GetEnseignantByIdRequest }
     * 
     */
    public GetEnseignantByIdRequest createGetEnseignantByIdRequest() {
        return new GetEnseignantByIdRequest();
    }

}
